version: "3.9"

services:
  paradox:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "${DOCKER_REGISTRY_HOST:-localhost}/lpaolini/paradox:${VERSION:-latest}"
    container_name: paradox
    init: true
    volumes:
      - "./paradox:/paradox/config"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    deploy:
      restart_policy:
        condition: on-failure
